name: Argo CD App Update on Release
description: Action to update an argo cd app manifest when a release is made in the source code
inputs:
  pat:
    description: PAT for accessing the application repo
    required: true
  cluster:
    description: Name of the cluster to deploy to
    required: true
  app-name:
    description: Name of the application to deploy
    required: true
  target-revision:
    description: Release tag of the application to deploy
    required: false
  image-tag:
    description: Image tag to use for the application
    required: false
runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        repository: beezlabs-org/k8s-landscape-apps
        token: ${{ inputs.pat }}

    - name: Set Target Revision
      if: inputs.target-revision
      uses: mikefarah/yq@v4.25.1
      with:
        cmd: yq -i '.${{ inputs.cluster }}.${{ inputs.app-name }}.targetRevision = "${{ inputs.target-revision }}"' './app-of-apps/values.yaml'

    - name: Set Release Id
      if: inputs.target-revision
      run: |
        echo "RELEASE_ID=${{ inputs.target-revision }}" >> $GITHUB_ENV
      shell: bash
      

    - name: Set Target Revision
      if: inputs.image-tag
      uses: mikefarah/yq@v4.25.1
      with:
        cmd: yq -i '.${{ inputs.cluster }}.${{ inputs.app-name }}.imageTag = "${{ inputs.image-tag }}"' './app-of-apps/values.yaml'

    - name: Set Release Id
      if: inputs.target-revision
      run: |
       echo "RELEASE_ID=${{ inputs.image-tag }}" >> $GITHUB_ENV
      shell: bash
    
    - name: Commit Changes
      env:
        GIT_AUTHOR_NAME: Beez Innovation Labs
        GIT_COMMITTER_NAME: Beez Innovation Labs
        GIT_AUTHOR_EMAIL: github@beezlabs.com
        GIT_COMMITTER_EMAIL: github@beezlabs.com
      run: |
        git add .
        git diff-index --quiet HEAD || git commit -m "feat: Update app manifest for ${{ inputs.app-name }} in cluster ${{ inputs.cluster }} for release $RELEASE_ID"
        git push
      shell: bash
